### ISSUE TITLE
Add table to sql database for saving mindmaps

### ISSUE THREAD

**Issue by rmoradc** [SE761Team4/jabref#36]
**User Story**

As a developer, I would like to have a table that represents the mindmap data so that I can save mind maps.
**Acceptance Criteria**

- Sql table in database that mindmaps can be saved to.

**Notes**

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**

**Describe the solution you'd like**

**Comment by koppor** [comment]
This is not necessary. See https://github.com/SE761Team4/jabref/issues/13.

Short version: Since the mindmap is stored using BibTeX, JabRef's storage capabilities are used. Since JabRef already can store in SQL, a mindmap is stored in SQL as soon as the mindmap is stored in JabRef (see https://github.com/SE761Team4/jabref/issues/23 for the interfaces)

**Comment by rmoradc** [comment]
I see. My mistake, thanks for catching that.
